### ISSUE TITLE
API Connection option for v2 / v3

### ISSUE THREAD

**Issue by funnelbeaker** [Alamion/obsidian-jira-sync#7]
Getting following error.

<img width="516" height="295" alt="Image" src="https://github.com/user-attachments/assets/3b311fdd-6f8b-448f-a7fc-b62d914f90bb" />

I see that api/v2 is hardcoded. Could you add an option for v3? Or an option to use a complete custom URL with nothing hardcoded?

**Comment by Alamion** [comment]
Hi, @funnelbeaker 
I think I'll let users choose the version of API in settings.

**Comment by Alamion** [comment]
Hi, @funnelbeaker
Done, check the results.

**Comment by venkivijay** [comment]
@Alamion It's still the same. I get the below error even when API Version 3 is selected in the settings.

<img width="551" height="615" alt="Image" src="https://github.com/user-attachments/assets/ac35987c-cfe0-444c-9cad-925347a7c7f7" />

**Comment by Alamion** [comment]
@venkivijay A slight confusion with the plugin version, now 1.3.2 is surely the latest one.
